language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get install libblas-dev liblapack-dev
install:
  - pip install -r requirements.txt
  - pip install numpy
  - pip install scipy
script: nosetests